title: Settings
fields:
  -
    handle: debug
    field:
      type: toggle
      display: Debug
  -
    handle: css_class
    field:
      options:
        privacy: Impressum/Datenschutz
      type: select
      display: 'CSS Class'
  -
    handle: template
    field:
      type: template
      display: Template
  -
    handle: layout
    field:
      type: template
      display: Layout
