title: Settings
fields:
  -
    handle: debug
    field:
      type: toggle
      display: Debug
  -
    handle: css_class
    field:
      options:
        privacy: Datenschutz
        imprint: Impressum
        contact: Kontakt
        exhibitions: Ausstellungen
        exterior: Draussen
        images: 'Bilder ohne Legenden'
      type: select
      display: 'CSS Class'
  -
    handle: template
    field:
      type: template
      display: Template
  -
    handle: layout
    field:
      type: template
      display: Layout
